[Writable]
LogLevel = 'INFO'

[Service]
Host = "172.17.0.1"
Port = 49996
ConnectRetries = 20
Labels = []
OpenMsg = "device serial go started"
Timeout = 5000
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = "172.17.0.1"
Port = 8500
Type = "consul"
CheckInterval = "10s"
FailLimit = 3
FailWaitTime = 10

[Clients]
  [Clients.Data]
  Name = "edgex-core-data"
  Protocol = "http"
  Host = "172.17.0.1"
  Port = 48080
  Timeout = 5000

  [Clients.Metadata]
  Name = "edgex-core-metadata"
  Protocol = "http"
  Host = "172.17.0.1"
  Port = 48081
  Timeout = 5000

  [Clients.Logging]
  Name = "edgex-support-logging"
  Protocol = "http"
  Host = "172.17.0.1"
  Port = 48061

[Device]
  DataTransform = true
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = "./res"

[Logging]
EnableRemote = false
File = "./device-serial-go.log"

# Pre-define Devices
#[[DeviceList]]
#  Name = "intelligent-PDU"
#  Profile = "XY-G10-485-4port"
#  Description = "Serial Device Intelligent-power"
#  Labels = [ "industrial" ,"PDU" ]
#  [DeviceList.Protocols]
#    [DeviceList.Protocols.other]
#      controlProtocolId="5"
#      serialPort = "/dev/ttyS2"
#      baudRate = "9600"
#      dataBits = "8"
#      stopBits = "1"
#      parity = "N"
#      unitId = "1"
